Adding Steps 1 & 4, fixing grid in step 3
ajoherron/GISTEMP_rewrite pull request #6
Opened 2023-10-31 17:50 UTC by ajoherron

First draft of Steps 1 (filtering data) and 4 (creation of SST dataset), as well as updating step 3 (from -180:180 longitude range to 0:360, in order to match ERSST grid)

2023-10-31 20:34 UTC, mhendri requested changes
Added some general comments. I appreciate the well commented and clear code. Runs nominally on my local machine.

2023-10-31 20:34 UTC, mhendri commented on steps/step1.py
> +Determined using configuration file (drop_rules.py).
is this a reference to drop_rules.csv which may one day become drop_rules.py?

2023-10-31 20:34 UTC, mhendri commented on parameters/__pycache__/constants.cpython-311.pyc
Can we remove this __pycache__ directories and files? You'll likely have to do a ```git rm -r --cached <folder>```

https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

2023-10-31 20:34 UTC, mhendri commented on parameters/constants.py
> +nearby_station_radius = 1200.0
just an out loud reminder that we'll want to make this command line configurable or an optional override or something else

2023-10-31 20:34 UTC, mhendri commented on steps/step4.py
> +    local_file = "sst.mnmean.nc"
can we pop this into an outputs or results directory?

2023-11-01 14:15 UTC, ajoherron commented on steps/step1.py
> +Determined using configuration file (drop_rules.py).
Yes, good catch! I was originally storing the Ts.strange rules as a string in drop_rules.py, ended up switching to a csv (drop_rules.csv).

2023-11-01 14:19 UTC, ajoherron commented on parameters/constants.py
> +nearby_station_radius = 1200.0
Definitely agree! I was thinking about adding in command line args with argparse after getting a draft of each of the steps ready

2023-11-01 14:23 UTC, ajoherron commented on steps/step4.py
> +    local_file = "sst.mnmean.nc"
If we're removing this temporary file a few lines down, is it worth adding this to a output/results directory?

line 60: os.remove(local_file)

2023-11-01 14:36 UTC, mhendri commented on steps/step4.py
> +    local_file = "sst.mnmean.nc"
Aha - I see that now. It did not remove it from my project directory when I ran it. I ran the program from the top level directory: ```python main/run.py``` so maybe that caused the issue. 

In any case, not worth adding it to a directory if it's being removed.

2023-11-01 14:49 UTC, ajoherron commented on parameters/__pycache__/constants.cpython-311.pyc
Can do, I can also change __pycache__ to __pycache__/ to make sure the directory and its contents are ignored.

2023-11-01 15:43 UTC, mhendri commented on parameters/constants.py
> +nearby_station_radius = 1200.0
Bit of a form thing, these should all be capitalized because they're constants.

2023-11-01 15:43 UTC, Mte2112 commented on parameters/__pycache__/constants.cpython-311.pyc
Can we add to the .gitignore file too? This necessary?

2023-11-01 15:50 UTC, ajoherron commented on parameters/constants.py
> +nearby_station_radius = 1200.0
Good call, I'll update all the code to have capital case for constants

2023-11-01 15:54 UTC, ajoherron commented on parameters/__pycache__/constants.cpython-311.pyc
@Mte2112 .gitignore will stop untracked files from being added, but Git will continue tracking any files that are currently being tracked. In addition to updating the .gitignore, I'll be sure to stop git from tracking folders using git rm -r --cached <folder>

2023-11-01 16:31 UTC, merged